services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - DB_HOST=postgres_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=employee_management
      - DB_PORT=5432
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=employee_management
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: